### ISSUE TITLE
Reformat autos for consistency with paths

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/envsetup#28]
### Background Information

In the current implementation, autos follow a different hierarchy in the YAML than paths - which leads to some inconsistency. 

For example:
```
```
default:
  paths:
    data: !expr list(
      DEV = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "DEV", "data"),
      QA = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "QA", "data"),
      PROD = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "PROD", "data")
      )
  autos:
    DEV:  !expr file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "DEV", "functions")
    QA: !expr file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "QA", "functions"),
    PROD: !expr file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "PROD", "functions")
    GLOBAL: !expr file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "global", "functions")
```

A more consistent format would look like:

```
default:
  paths:
    data: !expr list(
      DEV = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "DEV", "data"),
      QA = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "QA", "data"),
      PROD = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "PROD", "data")
      )
  autos:
    projects: !expr list(
      "DEV" = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "DEV", "functions"),
      "QA"= file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "QA", "functions"),
      "PROD" = file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "PROD", "functions")
      )
    global: !expr file.path(Sys.getenv("ENVSETUP_PROJECT_PATH"), "global", "functions")
```

In this example, the hierarchical autos is projects would be filtered by ENVSETUP_ENVIRON, but global would always appear. 

### Definition of Done

This shouldn't break existing functionality - but existing YAML files expecting filtering based on the YAML element names would need to be updated.

**Comment by nicholas-masel** [comment]
Closed by #52
