### ISSUE TITLE
`library()` fails if rprofile wasn't run

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/envsetup#29]
### What happened?

If `rprofile()` wasn't run, then library has no config to find and restore autos from. 

Automatically detecting autos and replacing them isn't possible because there's no saved path to search, so you need to bypass completely if there aren't any autos, and if there are then search to see if `envsetup:paths()` exists which is there if rprofile was run.

**Comment by nicholas-masel** [comment]
Closed with #27
