### ISSUE TITLE
Bug: Failing tests because MASS not available 

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/envsetup#39]
### What happened?

The error is encountered in tests right [here](https://github.com/pharmaverse/envsetup/actions/runs/4256602677/jobs/7405693676#step:8:325).

**Comment by mstackhouse** [comment]
@nicholas-masel  I'm think we can use `utf8` instead because I can specifically see it was installed. I'm wondering if the CI build just does base and not recommended for some reason. We can see installed package [here](https://github.com/pharmaverse/envsetup/actions/runs/4256602677/jobs/7405693676#step:7:311)

**Comment by nicholas-masel** [comment]
Closed by #52
